### ISSUE TITLE
微信小程序开发工具升级到1.3.0，点击启动模拟器，一直在正在编译小程序

### ISSUE THREAD

**Issue by chatterzhao** [overtrue/vscode-miniapp-helper#66]
是编译不成功还是耗时比较长，如果是耗时比较长能否有进度条这样的交互，这样方便查看

**Comment by overtrue** [comment]
vscode 有模拟器？编译小程序是什么鬼？这个是 vscode 的代码补全插件哦亲

**Comment by chatterzhao** [comment]
![image](https://user-images.githubusercontent.com/11829944/79433344-90be4c80-7fff-11ea-974f-fb2f90778262.png)

怎么回事，它怎么打开的是你的项目？

**Comment by chatterzhao** [comment]
可能作者clone了你的代码， README.md里面issue链接没有改

**Comment by overtrue** [comment]
那你找原作者吧
